### ISSUE TITLE
DA.reset_lesson() drops schema

### ISSUE THREAD

**Issue by kevcisme** [databricks-academy/dbacademy#6]
The `reset_lesson()` method inside of the databricks academy helper drops a schema which is problematic.

Example in action:

1. Notebook A runs first. The `%run includes classroom set up` script kicks off, creates a schema
2. Notebook A creates a table and then stores it in Feature Store using `f"{DA.schema_name}.some_feature_table"
3. Notebook B runs after Notebook A. It starts with `%run incudes classroom set up`
4. The feature store table from Notebook A is dropped because DA.reset_lesson() drops schema
5. Notebook B cannot just run Notebook A, because the state of the schema is in flux

**Comment by SireInsectus** [comment]
@kevcisme This is by design. Feel free to ping me on Slack for more details. 

To implement this pattern, Notebook A would
- Notebook A would define the lesson name so that assets (e.g., the database name) are prescribed.
- Notebook A would be responsible for calling DA.reset_lesson() in the setup
- Notebook A would NOT call DA.cleanup() at the end so that the state is preserved for the next notebook
- Notebook B would define the same lesson name as used for Lesson A
- Notebook B would NOT call DA.reset_lesson() so that state is preserved from the previous notebook.
- Notebook B would call DA.cleanup() at the end, assuming it's the last in the sequence of notebooks for a single lesson.

**Comment by zbachore** [comment]
@kevcisme - Regarding this issue, I am taking the "Machine Learning with Databricks" course from Databricks Academy, and the Classroom-Setup-01 notebook fails on DA.reset_lessons() with an error message, "Workspace Feature Store has been deprecated in the Current workspace...." I appreciate it if you can suggest a fix for this issue.

**Comment by kevcisme** [comment]
@zbachore can you send the DBC? I can take a look

**Comment by zbachore** [comment]
@kevcisme - All the lessons in that ML course have similar issues, but attached is the dbc for one of them.
[data-preparation-for-machine-learning-with-databricks.zip](https://github.com/user-attachments/files/17296496/data-preparation-for-machine-learning-with-databricks.zip)

Thanks for looking into this!

**Comment by zbachore** [comment]
@kevcisme - if you've looked at it, would you please let me know if and when this can be fixed?

**Comment by zbachore** [comment]
@kevcisme - I looked at the github repo, and I suspect the feature_store_api.py file might be the root cause because it is pointing to /api/2.0/feature-store/feature-tables/search, which makes sense with the feature-store deprecation error message I was getting.
I really appreciate it if someone can look at this one and fix it.

**Comment by kevcisme** [comment]
@zbachore I looked into this but I don't see anything immediately obvious. I haven't worked at Databricks for quite some time, but if you could send an email to astrid.ng@databricks.com she can help get this resolved!

**Comment by kevcisme** [comment]
Best of luck and hope you are getting a lot out of the training.
